title: Name  # You can add your name here

logo: 1.png # Use a relative path to logo image 

description: Make Robots more intelligent - Writing High-level software for different robotic platforms. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: daizhonghuan@gmail.com # Allow visitors to contact you